version: 2
updates:
    - package-ecosystem: nuget
      directory: "/src/Fragment.NetSlum.Console"
      schedule:
          interval: weekly
      open-pull-requests-limit: 5
    - package-ecosystem: nuget
      directory: "/src/Fragment.NetSlum.Core"
      schedule:
          interval: weekly
      open-pull-requests-limit: 5
    - package-ecosystem: nuget
      directory: "/src/Fragment.NetSlum.Networking"
      schedule:
          interval: weekly
      open-pull-requests-limit: 5
    - package-ecosystem: nuget
      directory: "/src/Fragment.NetSlum.Persistence"
      schedule:
          interval: weekly
      open-pull-requests-limit: 5
    - package-ecosystem: nuget
      directory: "/src/Fragment.NetSlum.Server"
      schedule:
          interval: weekly
      open-pull-requests-limit: 5
    - package-ecosystem: nuget
      directory: "/src/Fragment.NetSlum.TcpServer"
      schedule:
          interval: weekly
      open-pull-requests-limit: 5
