version: '3.8'

services:
  fragment_mysql:
    image: 'mysql:8'
    ports:
      - '3308:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 'd3ve10pm3nt'
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-p$d3ve10pm3nt"]
      interval: 10s
      timeout: 5s
      retries: 5

  fragment_server:
    image: psrewired/fragment-netslum
    build:
      context: .
      target: final
    ports:
      - '12417:12417'  # Game Server
      - '5000:5000'    # Web API
    environment:
      - ASPNETCORE_URLS=http://+:5000
      - ConnectionStrings__Database=server=fragment_mysql;port=3306;database=fragment_redux;username=root;password=d3ve10pm3nt;
      - Serilog__MinimumLevel__Default=Information
    depends_on:
      fragment_mysql:
        condition: service_healthy
