name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build image and run tests
      run: docker build . --file Dockerfile --target testrunner --tag fragment-netslum:${{ github.ref_name }}-${{github.run_number}}
